// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext.kotlin_version = '2.2.20'
    ext.library_version = '1.0.8'

    repositories {
        mavenLocal()
        mavenCentral()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.0'
        classpath 'com.google.gms:google-services:4.4.3'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:3.0.6'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "de.undercouch:gradle-download-task:5.6.0"
    }
}

allprojects {
    repositories {
        mavenLocal()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        google()
    }

    version = "$library_version"
    group = 'com.github.richard-muvirimi'
}

// Make library module the default for JitPack
if (System.getenv("JITPACK")) {
    // JitPack should only build and publish the main library module
    defaultTasks 'library:publishToMavenLocal'
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}
